apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: menu-service
        image: menu-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
