apiVersion: apps/v1
kind: Deployment
metadata:
  name: reset-password-service
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: reset-password-service
  template:
    metadata:
      labels:
        app: reset-password-service
    spec:
      containers:
      - name: reset-password-service
        image: reset-password:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
