apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  type: NodePort
  selector:
    app: recommendation-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
