apiVersion: v1
kind: Service
metadata:
  name: reset-password-service
spec:
  type: NodePort
  selector:
    app: reset-password-service
  ports:
  - port: 8080
    targetPort: 5000
    nodePort: 30005
