apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
spec:
  type: NodePort
  selector:
    app: sentiment-analysis-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
