apiVersion: v1
kind: Service
metadata:
  name: validate-token-service
spec:
  type: NodePort
  selector:
    app: validate-token-service
  ports:
  - port: 8080
    targetPort: 5000
    nodePort: 30007
